{"name":"Local: try_except","url":"d:\\LEARNING\\LEARNING PYTHON\\SYNTAX_BASIC\\23_Exception Process in PYTHON\\try_except.py","tests":[{"id":1753755797193,"input":"","output":""}],"interactive":false,"memoryLimit":1024,"timeLimit":3000,"srcPath":"d:\\LEARNING\\LEARNING PYTHON\\SYNTAX_BASIC\\23_Exception Process in PYTHON\\try_except.py","group":"local","local":true}